version: '3'

services:
  piece-react:
    image: ${DOCKER_IMAGE_NAME}
    container_name: piece-react
    ports:
      - "${PORT}:${PORT}"
    networks:
      - piece-network
    restart: unless-stopped

networks:
  piece-network:
    external: true